# -*- Makefile -*-

# Adding debug options
EXTRA_CFLAGS += -DDEBUG

obj-m += xt_LUA.o

EXTRA_CFLAGS += -I$(src)/prot_buf_new
xt_LUA-y += xt_LUA_target.o \

xt_LUA-y += nf_lua.o \
			prot_buf_helpers.o \
			byte_array.o \
			controller.o \
			prot_buf_ethernet.o \
			prot_buf_icmp.o \
			prot_buf_ip.o \
			prot_buf_raw.o \
			prot_buf_tcp.o \
			prot_buf_udp.o \
			prot_buf_tftp.o \
			prot_buf_dynamic.o \


# Adding Lua Support
EXTRA_CFLAGS += -I$(src)/lua -I$(src)/lua/include 
xt_LUA-y += lua/lapi.o \
			lua/lbaselib.o \
			lua/lcode.o \
			lua/ldebug.o \
			lua/ldo.o \
			lua/ldump.o \
			lua/lfunc.o \
			lua/lgc.o \
			lua/llex.o \
			lua/lmem.o \
			lua/lobject.o \
			lua/lopcodes.o \
			lua/lparser.o \
			lua/lstate.o \
			lua/lstring.o \
			lua/lstrlib.o \
			lua/ltable.o \
			lua/ltablib.o \
			lua/ltm.o \
			lua/lundump.o \
			lua/lvm.o \
			lua/lzio.o \
			lua/lauxlib.o \

# Lua exception handling
xt_LUA-y += lua/setjmp.o

# on 64bit machine
# xt_LUA-y += lua/setjmp_64.o
